name: Controllo grammaticale

on:
    pull_request:
        types: [opened, reopened]
jobs:
    controllo_grammaticale:
        if: startsWith(github.head_ref, 'feature/')
        runs-on: ubuntu-latest
        env:
            GH_TOKEN: ${{ secrets.PAT_CONTR_GRAM }}
        steps:
            - name: Clona repository
              run: | 
                gh repo clone https://github.com/Pedro-Leonii/sorgenti

            - name: Installa aspell
              run: |
                sudo apt-get install aspell
                sudo apt-get install aspell-it

            - name: Controllo grammaticale
              run: |
                cd sorgenti
                git checkout ${{ github.head_ref }}
                bash .github/scripts/errori.sh

            - name: Aggiunge il commento con errori
              run: |
                cd sorgenti
                gh pr comment ${{ github.event.pull_request.number }} -F errori.md


