name: deploy dei file LaTeX compilati nel repository destinazione

on:
    push: 
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIR_TO_DEL: ${{vars.DIR_TO_DEL}}
        runs-on: ubuntu-latest
        steps:
            - name: Clone source repository
              uses: actions/checkout@v4
              with:
                path: src
            
            - name: Setup tex path
              id: setup_tex
              run: |
                    echo "TEX_PATH<<EOF" >> $GITHUB_OUTPUT
                    echo "$(find -type f -name "*.tex" | grep -v $(echo $DIR_TO_DEL | sed "s/\s/|/g"))" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT
                  
            - name: view tex path
              run: echo ${{ steps.setup_tex.outputs.TEX_PATH }}
            
           
