name: deploy dei file LaTeX compilati nel repository destinazione

on:
    push: 
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIR_TO_DEL: ${{vars.DIR_TO_DEL}}
        runs-on: ubuntu-latest
        steps:
            - name: Clone source repository
              uses: actions/checkout@v4
              with:
                path: src
            
            - name: Setup tex path
              id: setup_tex
              run: echo "TEX_PATH=$(find -type f -name "*.tex")" >> $GITHUB_OUTPUT

              
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                working_directory: src
                root_file: |
                    ${{ steps.setup_tex.outputs.TEX_PATH }}
            
            - name: View results in src
              run: ls -R src
              
            - name: Clone compiled repository
              uses: actions/checkout@v4
              with:
                repository: Pedro-Leonii/compilati
                path: dst
                token: ${{ secrets.PAT_COMPILATI }}
                
            - name: Remove usless files 
              run: bash src/script.sh

            - name: View results in dst
              run: ls -R dst

            - name: Commit compiled
              uses: EndBug/add-and-commit@v9
              with:
                cwd: dst
