name: deploy dei file LaTeX compilati nel repository destinazione

on:
    push: 
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIR_TO_DEL: ${{vars.DIR_TO_DEL}}
        runs-on: ubuntu-latest
        steps:
            - name: Clone source repository
              uses: actions/checkout@v4
              with:
                path: src
                
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                working_directory: src
                root_file: "*.tex"
            
            - name: Clone compiled repository
              uses: actions/checkout@v4
              with:
                repository: Pedro-Leonii/compilati
                path: dst
                token: ${{ secrets.PAT_COMPILATI }}
                
            - name: Remove usless files 
              run: bash src/script.sh

            - name: View results
              run: ls -r dst

            - name: Commit compiled
              uses: EndBug/add-and-commit@v9
              with:
                cwd: dst
