name: deploy dei file LaTeX compilati nel repository destinazione

on:
     pull_request:
        branches:
          - main 
        types:
          - synchronize
     workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIR_TO_DEL: ${{vars.DIR_TO_DEL}}
        runs-on: ubuntu-latest
        steps:
            - name: Clone source repository
              uses: actions/checkout@v4
              with:
                  path: src
                  ref: ${{github.head_ref}}
            
            - name: Copy content
              run: |
                  cp src/* to_compile
                  
            - name: Setup tex path
              id: setup_tex
              run: |
                    echo "TEX_PATH<<EOF" >> $GITHUB_OUTPUT
                    echo "$(find -type f -name "to_compile/*.tex" | grep -v $(echo $DIR_TO_INGORE | sed 's/ /\\|/g'))" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT
                  
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                work_in_root_file_dir: true
                root_file: |
                    ${{ steps.setup_tex.outputs.TEX_PATH }}
      
            - name: Remove usless files in src
              run: |
                cd to_compile
                rm -rf DIR_TO_INGORE
                find * -type f ! -name "*.pdf" -delete
                cd ..
                
            - name: Update main branch
              run: |
                  cp to_compile/* src
                  cd src
            
            - name: Commit compiled
              uses: EndBug/add-and-commit@v9
              with:
                default_author: github_actor
                
