name: deploy dei file LaTeX compilati nel repository destinazione

on:
    push: 
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIR_TO_DEL: ${{vars.DIR_TO_DEL}}
        runs-on: ubuntu-latest
        steps:
            - name: Clone source repository
              uses: actions/checkout@v4
              with:
                path: src
                fetch-depth: 0
                
            - name: get modified files
              id: changed
              uses: tj-actions/changed-files@v45
              with:
                include_all_old_new_renamed_files: true
                path: src

            - name: view renamed files
              run: echo "${{steps.changed.all_old_new_renamed_files}}"
                  
                 
