name: deploy dei file LaTeX compilati nel repository destinazione

on:
    push: 
        branches:
            - main
    workflow_dispatch:
    
jobs:
    deploy_compiled:
        env: 
            DIRS_TO_IGNORE: ${{vars.DIRS_TO_IGNORE}}
            DIRS_TO_DEL: ${{vars.DIRS_TO_DEL}}
            
        runs-on: ubuntu-latest
        steps:
            - name: Clone source repository
              uses: actions/checkout@v4
              with:
                path: src

            - name: Clone compiled repository
              uses: actions/checkout@v4
              with:
                repository: Pedro-Leonii/compilati
                path: dst
                token: ${{ secrets.PAT_COMPILATI }}
            
            - name: Setup tex path
              id: setup_tex
              run: |
                    echo "TEX_PATH<<EOF" >> $GITHUB_OUTPUT
                    echo "$(find -type f -name "*.tex" | grep -v $(echo ${DIRS_TO_IGNORE} ${DIRS_TO_DEL}| sed 's/ /\\|/g'))" >> $GITHUB_OUTPUT
                    echo "EOF" >> $GITHUB_OUTPUT
                  
            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v3
              with:
                work_in_root_file_dir: true
                root_file: |
                    ${{ steps.setup_tex.outputs.TEX_PATH }}
      
            - name: Remove usless files in src
              run: |
                cd src
                rm -rf $DIRS_TO_DEL
                find * -type f ! -name "*.pdf" -delete
                cd ..
                
            - name: Copy ignored directories
              run: |
                  for d in $DIRS_TO_IGNORE; do
                    dest_dir = $(find ./dst -type d "*${d}")
                    echo "${dest_dir}"
                  done
            
            - name: Copy in dst
              run: cp -r src/* dst
            
            - name: Commit compiled
              uses: EndBug/add-and-commit@v9
              with:
                cwd: dst
